apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onlinecodeanalyzer.fullname" . }}
  labels:
    app: {{ include "onlinecodeanalyzer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "onlinecodeanalyzer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onlinecodeanalyzer.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: DEBUG
              value: "{{ .Values.config.debug }}"