image:
  repository: ksverchkov/onlinecodeanalyzer
  tag: latest
  pullPolicy: IfNotPresent
 
service:
  type: ClusterIP
  port: 80
 
ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  path: /onlinecodeanalyzer(/|$)(.*)
  hosts:
    - onlinecodeanalyzer.example.com
 
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
 
config:
  debug: false